name: Curl POST API with Basic Auth and Access Specific Field in Response Body
on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different
  workflow_dispatch:

jobs:
  run_curl_post_command:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

    steps:    

    - name: Fetch App Token
      id: fetch-app-token
      shell: bash
      run: |
        response=$(curl -X POST -H "Content-Type: text/plain" --data "grant_type=client_credentials&scope=TDriveTestApp" -u "9de1495b-2616-4c99-9197-2857b190f687:bf3a16100d2842e6bc5b48cc8a8f131f" "https://id.trimble.com/oauth/token")
        app_token=$(echo "$response" | jq -r '.access_token')
        echo "app_token=$app_token" >> $GITHUB_OUTPUT
        echo $app_token
