name: Curl POST API with Basic Auth and Access Specific Field in Response Body
on:
  push:
    branches:
      - main  # Replace 'main' with your default branch name if different
  workflow_dispatch:

jobs:
  run_curl_post_command:
    runs-on: ubuntu-latest  # You can choose a different runner if needed

   
